config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "pages#home"
  get 'about', to: 'pages#about'
  resources :books
  get 'register', to: 'users#new'
  resources :users, except: [:new]
  get 'admin', to: 'users#getadmin'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :addresses, path: 'addresses', except: [:destroy]
  
  resources :orders, except: [:create, :update, :edit]
  get 'place_order', to: 'orders#edit'
    get 'adminorders', to: 'orders#adminorders'
    get 'paymentorder', to: 'orders#paymentorder'
    get 'shipmentorder', to: 'orders#shipmentorder'
    get 'showorderitems', to: 'orders#showorderitems'
    get 'downloadorder', to: 'orders#download'

  resources :item_orders, only: [:destroy]
  get 'item_orders', to: 'item_orders#create'
  get 'edit_item_orders', to: 'item_orders#edit'

  resources :deliveries
  resources :opinions, except: [:edit, :update, :destroy]
  resources :categories
  resources :messages
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many    :orderitems
    has_one :delivery
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    require 'date'
    before_action :require_address, only: [:edit]
    before_action :require_admin, only: [:paymentorder, :shipmentorder, :adminorders, :showorderitems]
           #caches_page :showorderitems
   def new
    if logged_in?
        if Order.exists?(:user_id => "#{current_user.id}", :status => "Koszyk")
            session[:order_id] = Order.find_by(user_id: "#{current_user.id}", status: "Koszyk").id
        else
            @order = Order.new(user_id: current_user.id, status:"Koszyk", total: 0)
            if @order.save
                session[:order_id] = @order.id
            end
        end
        redirect_to root_path
    end
   end
   def edit
       if current_user.id != Order.find_by(id: session[:order_id]).user_id
          flash[:danger] = "To nie twoje zamówienie"
          redirect_to root_path
       else
          @order = Order.find_by(id: session[:order_id])
          @order.delivery_id = params[:delivery]
          @order.total = @order.total + Delivery.find(params[:delivery]).price.to_f
          @items = OrderItem.where("order_id = #{session[:order_id]}")
          @items.each do |item|
             @book = Book.find_by(id: item.book_id)
             @book.copies = @book.copies - item.quantity
             if @book.copies < 0 
                 flash[:danger] = "Nie możemy zrealizować tego zamówienia"
                 redirect_to order_path
             end
          end
          @items.each do |item|
             @book = Book.find_by(id: item.book_id)
             @book.copies = @book.copies - item.quantity
             @book.save
          end
          @order.status = "Do zapłaty"
          @order.save
          flash[:success] = "Złożono zamówienie."
          redirect_to new_order_path
       end
   end
   def index
       @orders = Order.where("user_id = #{current_user.id} AND status NOT LIKE 'Koszyk'")
   end
   def adminorders
       @orders = Order.where("status NOT LIKE 'Koszyk'").order("status ASC")
   end
   def paymentorder
      @order = Order.find(params[:id]) 
      @order.status = "Realizowanie"
      @order.save
      flash[:success] = "Zmieniono status"
      redirect_to adminorders_path
   end
   def shipmentorder
      @order = Order.find(params[:id]) 
      @order.status = "Wysłano"
      @order.save
      flash[:success] = "Zmieniono status"
      redirect_to adminorders_path
   end
   def showorderitems
       @order = Order.find(params[:id])
       @items = OrderItem.where("order_id = #{params[:id]}")
       @address = Address.find_by(user_id: @order.user_id)
   end
   def update
       
   end
   def destroy
       
   end
   def show
       @deliveries = Delivery.all
       if current_user.id != Order.find_by(id: session[:order_id]).user_id
          flash[:danger] = "To nie twoje zamówienie"
          redirect_to root_path
       else
           @order_items = OrderItem.search(session[:order_id])
           tot = 0
           @order_items.each do |item|
               tot = Book.find_by(id: item.book_id).price*item.quantity + tot
           end
           @order = Order.find_by(id: session[:order_id])
           @order.total = tot
           @order.save
       end
   end
    def download
        require "prawn"
        #require "prawn/tables"
        @order = Order.find(params[:id])
        @items = OrderItem.where("order_id = #{@order.id}")
        @address = Address.find_by(user_id: @order.user_id)
        if File.exists?("public/pdfs/faktura #{@order.id}.pdf")
            send_file "public/pdfs/faktura #{@order.id}.pdf", :type=>"application/pdf", :x_sendfile=>true
        else
            generate_pdf(@order, @items, @address)
            send_file "public/pdfs/faktura #{@order.id}.pdf", :type=>"application/pdf", :x_sendfile=>true
        end
        
    end
   private
   def require_address
      if current_user.address
          
      else
          flash[:danger] = "Musisz dodać adres do swojego konta."
          redirect_to addresses_path
      end
   end
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Tylko admin może zrobić coś takiego"
            redirect_to root_path
        end
    end
    def generate_pdf(order, items, address)
        books = Array.new
        total = 0
        items.each do |item|
            hash = Hash.new
           @book = Book.find(item.book_id)
           hash["title"] = @book.title
           hash["author"] = @book.author
           hash["publisher"] = @book.publisher
           hash["price"] = @book.price * item.quantity
           total += hash["price"]
           hash["quantity"] = item.quantity
           books << hash
        end
        total+= Delivery.find(order.delivery_id).price
        
        Prawn::Document.generate("public/pdfs/faktura #{order.id}.pdf") do
              font_families.update("Arial" => {
                :normal => "app/assets/fonts/Arial.ttf",
                :italic => "app/assets/fonts/Arial Italic.TTF",
              })
            font "Arial"

            # Defining the grid 
            # See http://prawn.majesticseacreature.com/manual.pdf
            define_grid(:columns => 5, :rows => 8, :gutter => 10) 
            
            grid([0,0], [1,1]).bounding_box do 
              text  "Faktura", :size => 18
              text "Faktura numer: #{order.id}", :align => :left
              text "Data: #{Date.today.to_s}", :align => :left
              move_down 10
              
              text "Nabywca "
              text "#{User.find(address.user_id).username}"
              text "telefon: #{address.telnumber}"
              text "email: #{User.find(address.user_id).email}"
            end
            
            grid([0,3.6], [1,4]).bounding_box do 
              # Company address
              #move_down 10
              text "BookShopOnline", :align => :left
              text "Adres", :align => :left
              text "Nowoursynowska 161", :align => :left
              text "02-787 Warszawa", :align => :left
              text "Lubelskie", :align => :left
              text "Tel No: 22312512123", :align => :left
            end
            
            text "Szczegóły faktury"#, :style => :arial
            stroke_horizontal_rule
            move_down 10
            items = [["No","Tytuł", "Autor", "Cena"]]
            items += books.each_with_index.map do |h, i|
              [
                i + 1,
                h["title"],
                h["author"],
                h["price"],
              ]
            end
            items += [["", "", "Przesyłka", "#{Delivery.find(order.delivery_id).price}"]]
            items += [["", "", "Razem", "#{total}"]]
            
            
            table items, :header => true, 
              :column_widths => { 0 => 50, 1 => 150,2 => 200, 3 => 100}, :row_colors => ["d2e3ed", "FFFFFF"] do
                style(columns(3)) {|x| x.align = :right }
              end
            move_down 40
            text "Sposób dostawy: #{Delivery.find(order.delivery_id).title}", :style => :italic
            
            move_down 20
            text "..............................."
            text "Podpis"
            
            move_down 10
            stroke_horizontal_rule
            
            bounding_box([bounds.right - 50, bounds.bottom], :width => 60, :height => 20) do
              pagecount = page_count
              text "Strona #{pagecount}"
            end

        end
    end
end

app/views/orders/adminorders.html.erb
<% if @orders.any? %>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Nazwa użytkownika</th>
            <th>Ostatnia aktualizacja</th>
            <th>Kwota</th>
            <th>Rodzaj przesyłki</th>
            <th>Status</th>
        </tr>
        <% @orders.each do |order| %>
        <tr>
            <td><%= link_to "#{order.id}", showorderitems_path(:id => "#{order.id}"), class:'btn btn-xl btn-primary' %></td>
            <td><%= User.find(order.user_id).username %></td>
            <td><%= order.created_at.strftime( "%F %T ") %></td>
            <td><%= order.total %></td>
            <td><%= Delivery.find(order.delivery_id).title %></td>
            <td><%= order.status %></td>
            <% if order.status != "Wysłano" %>
            <td><%= order.status =="Realizowanie" ? (link_to "wysłano", shipmentorder_path(:id => "#{order.id}") ,class: "btn btn-xs btn-info") : (link_to "zapłacono", paymentorder_path(:id => "#{order.id}"), class: "btn btn-xs btn-default") %></td>
            <% end %>
        </tr>
        <% end %>
    </table>
<% end %>

app/views/orders/index.html.erb
<h1 align="center">Twoje zamówienia</h1>
<div class="row">
    <div class="col-xs-12">
        <div class="col-sm-1">Nr zamówienia</div>
        <div class="col-sm-2">Kwota</div>
        <div class="col-sm-2">Sposób dostawy</div>
        <div class="col-sm-2">Ostatnie działanie</div>
        <div class="col-sm-2">Status</div>
        <div class="col-sm-2">Faktura</div>
    </div>
</div>
<div class="row">
    <% @orders.each do |order| %>
        <div class="col-xs-12">
            <div class="col-sm-1"><%= order.id %></div>
            <div class="col-sm-2"><%= order.total %></div>
            <div class="col-sm-2"><%= Delivery.find_by(id: order.delivery_id).title %></div>
            <div class="col-sm-2"><%= order.updated_at.strftime( "%F %T ") %></div>
            <div class="col-sm-2"><%= order.status %></div>
            <div class="col-sm-2">
            <% if order.status != "Do zapłaty" %>
            <%= link_to "Pobierz",
              downloadorder_path(:id => "#{order.id}"),
              target: "_blank",
              class: "btn btn-xs btn-info" %>
              
            <% end %>
            </div>
        </div>
    <% end %>
</div>                     

app/views/orders/pdf.html.erb
<div class='container'>
    <table class='table table-striped'>
        <tr>
            <th>Tytuł</th>
            <th>Autor</th>
            <th>Wydawca</th>
            <th>Rok Wydania</th>
            <th>ISBN</th>
            <th>Liczba Stron</th>
            <th>Liczba sztuk</th>
        </tr>
        <% @items.each do |item| %>
        <tr>
            <td><%= Book.find(item.book_id).title %></td>
            <td><%= Book.find(item.book_id).author %></td>
            <td><%= Book.find(item.book_id).publisher %></td>
            <td><%= Book.find(item.book_id).pdate %></td>
            <td><%= Book.find(item.book_id).isbn %></td>
            <td><%= Book.find(item.book_id).pages %></td>
            <td><%= item.quantity %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/orders/show.html.erb
<% if !OrderItem.where(order_id: session[:order_id]).empty? %>
<%= @order.status + " nr zamówienia #{session[:order_id]}" %>
<table class='table'>
    <th>Tytuł</th>
    <th>Cena</th>
    <th>Ilość</th>
    <% @order_items.each do |item| %>
    <tr>
        <td><%= Book.find_by(id: item.book_id).title %></td>
        <td><%= Book.find_by(id: item.book_id).price %> PLN</td>
        <td>
            <%= form_tag(edit_item_orders_path, :method => 'get') do %>
            <%= number_field_tag 'quantities', item.quantity, min: 1, max: Book.find_by(id: item.book_id).copies, class: 'form-control' %>
            <%= hidden_field_tag 'book', item.book_id %>
            <%= submit_tag "Edytuj", class: 'btn btn-primary' %>
            <% end %>
        </td>
        <td><%= link_to "Usuń", item_order_path(item.id), method: :delete, class: 'btn btn-danger' %></td>
    </tr>
    <% end %>
</table>
<div class="row">
        <div class="col-sm-offset-9 col-sm-3">
            <h1>Razem: </h1><h3><%= @order.total %> PLN</h3>        
        </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <%= form_tag(place_order_path, :method => "get") do %>
            <div class="col-sm-3">
                Wybierz sposób dostawy:
            </div>
            <div class="col-sm-3">
                <%= select_tag "delivery", options_from_collection_for_select(@deliveries, "id", "title"), class: 'form-control' %>
                </div>
        <div class="col-xs-12">
            <%= submit_tag "Złóż zamówienie", class: 'btn-lg btn-success' %>
        </div>
        
        <% end %>
    </div>
</div>
<% else %>
<h2>Dodaj książki do zamówienia...</h2>
<% end %>

app/views/orders/showorderitems.html.erb
<div class='container'>
    <table class='table'>
        <tr>
            <th>Tytuł</th>
            <th>Autor</th>
            <th>Wydawca</th>
            <th>Rok Wydania</th>
            <th>ISBN</th>
            <th>Liczba Stron</th>
        </tr>
        <% @items.each do |item| %>
        <tr>
            <td><%= Book.find(item.book_id).title %></td>
            <td><%= Book.find(item.book_id).author %></td>
            <td><%= Book.find(item.book_id).publisher %></td>
            <td><%= Book.find(item.book_id).pdate %></td>
            <td><%= Book.find(item.book_id).isbn %></td>
            <td><%= Book.find(item.book_id).pages %></td>
        </tr>
        <% end %>
    </table>
</div>
<h3>Dane do wysyłki:</h3>
<div><label>Ulica</label>
<%=@address.street%></div>
<div><label>Numer domu</label>
<%=@address.homenumber%></div>
<div><label>Numer mieszkania</label>
<%=@address.apartnumber%></div>
<div><label>Kod pocztowy</label>
<%=@address.postalcode%></div>
<div><label>Miejscowość</label>
<%=@address.city%></div>
<div><label>Numer telefonu</label>
<%=@address.telnumber%></div>
<h3>Wysyłka: <%= Delivery.find(@order.delivery_id).title %></h3>
<%= link_to "wyślij", shipmentorder_path(:id => "#{@order.id}") ,class: "btn btn-lg btn-success" %>