config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "pages#home"
  get 'about', to: 'pages#about'
  resources :books
  get 'register', to: 'users#new'
  resources :users, except: [:new]
  get 'admin', to: 'users#getadmin'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :addresses, path: 'addresses', except: [:destroy]
  
  resources :orders, except: [:create, :update, :edit]
  get 'place_order', to: 'orders#edit'
    get 'adminorders', to: 'orders#adminorders'
    get 'paymentorder', to: 'orders#paymentorder'
    get 'shipmentorder', to: 'orders#shipmentorder'
    get 'showorderitems', to: 'orders#showorderitems'
    get 'downloadorder', to: 'orders#download'

  resources :item_orders, only: [:destroy]
  get 'item_orders', to: 'item_orders#create'
  get 'edit_item_orders', to: 'item_orders#edit'

  resources :deliveries
  resources :opinions, except: [:edit, :update, :destroy]
  resources :categories
  resources :messages
end

app/models/book.rb
class Book < ApplicationRecord
   has_many :book_categories
   has_many :categories, through: :book_categories
   has_attached_file :avatar, styles: { medium: "300x150", thumb: "150x75" }, default_url: "/images/:style/missing.png"
   validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
    def self.search(search, category)
      where("LOWER(#{category}) LIKE '%#{search.downcase}%'")
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :require_admin, only: [:destroy, :edit, :update, :new, :create]
   ##
   #Wyświetla listę książek. Korzysta też z filtracji i wyszukiwania
   def index
       @books = Book.paginate(page: params[:page], per_page: 10)
       if params[:search]
          @books = Book.search(params[:search],params[:category]).order("price #{params[:price]}")
          @books = @books.paginate(page: params[:page], per_page: 10)
       end
       if params[:cat]
          category = Category.find(params[:cat])
          @books = category.books
          @books = @books.paginate(page: params[:page], per_page: 10)
       end
   end
   def new
       @book = Book.new
   end
   def create
       @book = Book.new(book_param)
       if @book.save
          flash[:success] = "Książka została prawidłowo dodana"
          redirect_to books_path
       else
          render 'new'
       end
   end
   def show
       @book = Book.find(params[:id])
       @book.counter += 1
       @book.save
       @opinions = Opinion.where(book_id: @book.id)
   end
   def edit
       @book = Book.find(params[:id])
   end
   def update
       @book = Book.find(params[:id])
       if @book.update(book_param)
          flash[:success] = "Pozycja została edytowana"
          redirect_to books_path
       else
          render 'edit'
       end
   end
   def destroy
       @book = Book.find(params[:id])
       if @book.destroy
         flash[:danger] = "Pozyzja została usunięta"
         redirect_to books_path
       else
          redirect_to books_path
       end     
   end
   private
   def book_param
      params.require(:book).permit(:title, :author, :publisher, :pdate, :isbn, :pages, :price, :copies, :avatar, category_ids: [])
   end
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Tylko admin może zrobić coś takiego"
            redirect_to root_path
        end
    end
end

app/views/books/_form.html.erb
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@book, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Tytuł</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :title, class: "form-control", placeholder: "Tytuł", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Autor</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :author, class: "form-control", placeholder: "Autor" %>
                </div>
            </div>
             <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Wydawca</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :publisher, class: "form-control", placeholder: "Wydawca" %>
                </div>
            </div>
             <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Data wydania</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :pdate, class: "form-control", placeholder: "Rok Wydania" %>
                </div>
            </div>
             <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>ISBN</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :isbn, class: "form-control", placeholder: "ISBN" %>
                </div>
            </div>
              <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Liczba stron</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :pages, class: "form-control", placeholder: "Liczba stron" %>
                </div>
            </div>
              <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Cena</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :price, class: "form-control", placeholder: "Cena" %>
                </div>
            </div>
              <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Egzemplarze</label>
                </div>
                <div class="col-sm-8">
                    <%= f.number_field :copies, class: "form-control", placeholder: "Egzemplarze" %>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-offset-2 col-sm-8">
                        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                        <% end %>
                    </div>
                </div>
            </div>
              <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Obrazek</label>
                </div>
                <div class="col-sm-8">
                     <%= f.file_field :avatar %>
                </div>
            </div>
           
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit "Dodaj książke", class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
            <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Anuluj i powróć do listy książek...", books_path %> ]
        </div>
    </div>
</div>

app/views/books/edit.html.erb
<div align='center'><h1>Edytuj Pozycję</h1></div>
<%= render 'layouts/errors', obj: @book %>
<%= render 'books/form' %>

app/views/books/index.html.erb
<% if !logged_in? %>
    <h2 align='center'><%= link_to "Zaloguj się, aby zamówić książki", login_path %></h2>
<% end %>
<h4>Kategorie: &nbsp;</h4>
                    <% Category.all.each do |category| %>
                        <%= link_to "#{category.name}", books_path(:cat => "#{category.id}"),class:"bnt btn-xs btn-info" %>
                    <% end %>
<div align="center"><%= will_paginate %></div>
<div class='container'>
    <table class='table'>
        <tr>
            <th>Okładka</th>
            <th>Kategoria</th>
            <th>Tytuł</th>
            <th>Autor</th>
            <th>Wydawca</th>
            <th>Rok Wydania</th>
            <th>ISBN</th>
            <th>Liczba Stron</th>
            <th>Cena</th>
            <th>Egzemplarze</th>
        </tr>
        <% if @books.present? %>
            <% @books.each do |b| %>
                <tr>
                    <td>
                        <%= link_to book_path(b) do %>
                        <%= image_tag b.avatar.url(:thumb) %>
                        <% end %>
                    </td>
                    <td>
                        <% b.categories.each do |c| %>
                        <span class="label label-primary"><%= c.name %></span></br>
                        <% end %>
                    </td>
                    <td>
                        <%= b.title %>
                    </td>
                    <td><%= b.author %></td>
                    <td><%= b.publisher %></td>
                    <td><%= b.pdate %></td>
                    <td><%= b.isbn %></td>
                    <td><%= b.pages %></td>
                    <td><%= b.price %> zł</td>
                    <% if b.copies >= 100 %>
                    <td><font color="green">Wysoka dostępność</font></td>
                    <% elsif b.copies > 10 && b.copies<100 %>
                    <td><font color="orange">Niska dostępność</font></td>
                    <% else %>
                    <td><font color="red">Brak</font></td>
                    <% end %>
                    <% if logged_in? && current_user.admin? %>
                    <td><%= link_to 'Edytuj', edit_book_path(b.id), class: "btn btn-xs btn-primary" %></td>
                    <td><%= link_to 'Usuń', book_path(b.id), method: :delete, class: "btn btn-xs btn-danger" %></td>
                    <% end %>
                    <% if logged_in? %>
                    <td>
                        <%= form_tag(item_orders_path, :method => 'get') do %>
                        <div class='form-group'>
                        <%= number_field_tag 'quantities', 1, min: 1, max: b.copies, class: 'form-control' %>
                        </div>
                        <%= hidden_field_tag 'book',  b.id %>
                        <%= submit_tag "Dodaj do koszyka", class: 'btn btn-success' %>
                        <% end %>
                    </td>
                    <% end %>
                </tr>
            <% end %>
              </table>
        <% else %>
            <p>Nie znaleziono</p>
        <% end %>

</div>
<div align="center"><%= will_paginate %></div>

app/views/books/new.html.erb
<h1 align='center'>Dodaj książkę do zbioru</h1>
<%= render 'layouts/errors', obj: @book %>
<%= render 'books/form' %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-sm-3">
      <div align='center'><%= image_tag @book.avatar.url(:medium) %></div>
      <table class="table table-striped">
          <thead>
              
          </thead>
          <tbody>
              <tr>
                  <td>
                      <label>Tytuł</label>
                  </td>
                  <td>
                      <%= @book.title %>
                  </td>
              </tr>
              <tr>
                  <td>
                      <label>Autor</label>
                  </td>
                  <td>
                      <%= @book.author %>
                  </td>                  
              </tr>
              <tr>
                  <td>
                      <label>Wydawca</label>
                  </td>
                  <td>
                      <%= @book.publisher %>
                  </td>
              </tr>
              <tr>
                  <td>
                      <label>Data wydania</label>
                  </td>
                  <td>
                      <%= @book.pdate %>
                  </td>                  
              </tr>
              <tr>
                  <td>
                      <label>ISBN</label>
                  </td>
                  <td>
                      <%= @book.isbn %>
                  </td>                    
              </tr>
              <tr>
                  <td>
                      <label>Strony</label>
                  </td>
                  <td>
                      <%= @book.pages %>
                  </td>                    
              </tr>
              <tr>
                  <td>
                      <label>Cena</label>
                  </td>
                  <td>
                      <%= @book.price %>
                  </td>
              </tr>
              <tr>
                  <td>
                      <label>Kategorie</label>
                  </td>
                  <td>
                    <% @book.categories.each do |category| %>
                        <%= link_to "#{category.name}", books_path(:cat => "#{category.id}"),class:"bnt btn-xs btn-info" %>
                    <% end %>
                      
                  </td>
              </tr>
              <tr>
                  <td>
                      <label>Średnia opinia</label>
                  </td>
                  <td>
                      <% if !@opinions.any? %>
                          Brak opinii
                      <% else %>
                          <%= @opinions.average(:rate) %>
                      <% end %>
                      
                  </td>
              </tr>
          </tbody>
      </table>
                    <% if logged_in? %>
                        <%= form_tag(item_orders_path, :method => 'get') do %>
                        <div class='form-group'>
                            <%= number_field_tag 'quantities', 1, min: 1, max: @book.copies, class: 'form-control' %>
                        </div>
                        <%= hidden_field_tag 'book',  @book.id %>
                        <div class="form-group">
                            <%= submit_tag "Dodaj do koszyka", class: 'btn btn-success' %>    
                        </div>
                        
                        <% end %>
                    <% end %>
                    <% if logged_in? && current_user.admin? %>
                    <p style="margin:3px;">
                        <%= link_to 'Edytuj', edit_book_path(@book.id), class: "btn btn-xs btn-primary" %>
                        <%= link_to 'Usuń', book_path(@book.id), method: :delete, class: "btn btn-xs btn-danger" %>                      
                    </p>

                    <% end %>
  </div>
  <div class="col-sm-9">
      
      <% if @opinions %>
            <% @opinions.each do |opinion| %>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                            Opinia użytkownika:
                            <b><%= "#{User.find(opinion.user_id).username}" %></b>
                        <span class="badge" align='left'><%= "Ocena: #{opinion.rate}/10"%></span>
                    </div>
                    <div class="panel-body">
                        <%= opinion.description %>
                        
                    </div>
                </div>
            <% end %>
        <% else %>
            Brak opinii...
        <% end %>
        <%= render "opinions/new" %>
  </div>

</div>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Anuluj i powróć do listy książek...", books_path %> ]
        </div>