config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "pages#home"
  get 'about', to: 'pages#about'
  resources :books
  get 'register', to: 'users#new'
  resources :users, except: [:new]
  get 'admin', to: 'users#getadmin'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :addresses, path: 'addresses', except: [:destroy]
  
  resources :orders, except: [:create, :update, :edit]
  get 'place_order', to: 'orders#edit'
    get 'adminorders', to: 'orders#adminorders'
    get 'paymentorder', to: 'orders#paymentorder'
    get 'shipmentorder', to: 'orders#shipmentorder'
    get 'showorderitems', to: 'orders#showorderitems'
    get 'downloadorder', to: 'orders#download'

  resources :item_orders, only: [:destroy]
  get 'item_orders', to: 'item_orders#create'
  get 'edit_item_orders', to: 'item_orders#edit'

  resources :deliveries
  resources :opinions, except: [:edit, :update, :destroy]
  resources :categories
  resources :messages
end

app/models/category.rb
class Category < ApplicationRecord
   has_many :book_categories
   has_many :books, through: :book_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, only: [:destroy, :edit, :update, :new, :create]
    before_action :set_category, only: [:edit, :update, :destroy, :show]
    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Utworzono kategorię"
            redirect_to categories_path
        else
            render 'new'
        end
    end
    def edit
        #set_category
    end
    def update
        #set_category
        if @category.update(category_params)
            flash[:success] = "Edytowano kategorię"
            redirect_to categories_path
        else
            render 'edit'
        end
    end
    def destroy
        #set_category
        if @category.destroy
            flash[:danger] = "Usunięto kategorię"
            redirect_to categories_path
        else
            render 'edit'
        end
    end
    def show
        #set_category
    end
    def index
        @categories = Category.all
    end
    private
    def set_category
        @category = Category.find(params[:id])
    end
    def category_params
       params.require(:category).permit(:name)
    end
    def require_admin
        if !logged_in? || (logged_in? and !current_user.admin?)
            flash[:danger] = "Tylko admin może zrobić coś takiego"
            redirect_to root_path
        end
    end
end

app/views/categories/_form.html.erb
<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                    <label>Tytuł</label>
                </div>
                <div class="col-sm-8">
                    <%= f.text_field :name, class: "form-control", placeholder: "nazwa", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <%= f.submit "Dodaj książke", class: 'btn btn-primary btn-lg' %>
                </div>
            </div>
            <% end %>
        <div class="col-xs-4 col-xs-offset-4">
            [ <%= link_to "Anuluj i powróć do listy książek...", books_path %> ]
        </div>
    </div>
</div>

app/views/categories/edit.html.erb
<h1 align='center'>Edytuj kategorię</h1>
<%= render 'layouts/errors', obj: @category %>
<%= render 'categories/form' %>

app/views/categories/index.html.erb
<h2 align='center'>Lista kategorii</h2>
<% @categories.each do |category| %>
    <div class="panel panel-info">
      <div class="panel-heading">
          <h4>
              <span class="label label-warning"><%= link_to category.name, category_path(category) %>  </span>
          </h4>
      </div>
      <div class="panel-body">
          <% category.books.each do |book| %>
          <ul class="list-group">
              <li class="list-group-item"><%= link_to "#{book.title}", book_path(book) %></li>
          </ul>
          <% end %>
      </div>
    </div>
<% end %>

app/views/categories/new.html.erb
<h1 align='center'>Dodaj kategorię</h1>
<%= render 'layouts/errors', obj: @category %>
<%= render 'categories/form' %>

app/views/categories/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
      <%= @category.name %>
  </div>
  <div class="panel-body">
      <% @category.books.each do |book| %>
      <ul class="list-group">
          <li class="list-group-item"><%= link_to "#{book.title}", book_path(book) %></li>
      </ul>
      <% end %>
  </div>
</div>