config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root "pages#home"
  get 'about', to: 'pages#about'
  resources :books
  get 'register', to: 'users#new'
  resources :users, except: [:new]
  get 'admin', to: 'users#getadmin'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :addresses, path: 'addresses', except: [:destroy]
  
  resources :orders, except: [:create, :update, :edit]
  get 'place_order', to: 'orders#edit'
    get 'adminorders', to: 'orders#adminorders'
    get 'paymentorder', to: 'orders#paymentorder'
    get 'shipmentorder', to: 'orders#shipmentorder'
    get 'showorderitems', to: 'orders#showorderitems'
    get 'downloadorder', to: 'orders#download'

  resources :item_orders, only: [:destroy]
  get 'item_orders', to: 'item_orders#create'
  get 'edit_item_orders', to: 'item_orders#edit'

  resources :deliveries
  resources :opinions, except: [:edit, :update, :destroy]
  resources :categories
  resources :messages
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container" align='center'>
<footer class="footer">
<small>
Copyright © <a href="https://github.com/danieln96/BookShopOnline" target="_blank">Book Shop Online</a>
by <a href="#">Daniel Niczyporuk</a>
</small>
</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%="#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">×</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BookShopOnline", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Lista książek", books_path %></li>
        <% if logged_in? && current_user.admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Panel Admina <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Dodaj książkę", new_book_path %></li>
            <li><%= link_to "Dodaj sposób dostawy", new_delivery_path %></li>
            <li><%= link_to "Lista użytkowników", users_path %></li>
            <li><%= link_to "Zamówienia", adminorders_path %></li>
            <li><%= link_to "Dodaj kategorię", new_category_path %></li>
          </ul>
        </li>
        <% end %>
        <li><%= link_to "Kategorie", categories_path %></li>
      </ul>
      <%= form_tag(books_path, :method => "get", class: 'navbar-form navbar-left' ) do %>
      <div class="form-group">
      <%= text_field_tag :search, params[:search], placeholder: "Wyszukaj książkę", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= select_tag "category", options_for_select([["Tytuł","title"], ["Autor","author"], ["Wydawca", "publisher"], ["Data wydania","pdate"], ["ISBN", "isbn"]], "Książka"), class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= select_tag 'price', options_for_select([["Cena rosnąco", "ASC"],["Cena malejąco", "DESC"]]), class: 'form-control' %>
      </div>
      <%= submit_tag "Wyszukaj", class: 'btn btn-success' %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Panel użytkownia <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Adres dostawy", addresses_path %></li>
            <li><%= link_to "Rodzaje przesyłek", deliveries_path %></li>
            <li><%= link_to "Twoje zamówienia", orders_path %> </li>
          </ul>
        </li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Zamówienie nr #{session[:order_id]}", order_path(session[:order_id]) %></li>
          <li><%= link_to "Wyloguj", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Zaloguj", login_path %></li>
          <li><%= link_to "Zarejestruj", register_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book Shop Online</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
<div class="container">
<%= render 'layouts/messages' %>
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/order_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>Faktura</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>